name = "open-wegram-bot"
main = "src/worker.js"
compatibility_date = "2023-05-18"
keep_vars = true

[placement]
mode = "smart"

# Specify environment variables for your main production environment
[vars]
PREFIX = "789"
SECRET_TOKEN = "aGTUMHeaN8LOrcbc"
# SECRET_TOKEN will be configured via Cloudflare Dashboard

# Define a staging environment for testing
[env.staging]
name = "open-wegram-bot-staging"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[env.staging.vars]
PREFIX = "staging"
# SECRET_TOKEN will be configured via Cloudflare Dashboard